language: java

jdk:
  - oraclejdk11

script:
  - ./gradlew build dokka

after_success:
  # CODECOV_TOKEN is set as environmental variable in travis
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN