package org.grigoryfedorov.geolibrary

private const val EQUAL_ACCURACY = 0.000001

const val ANGLE_EQUAL_ACCURACY = EQUAL_ACCURACY
const val ELEVATION_EQUAL_ACCURACY = EQUAL_ACCURACY
const val DISTANCE_EQUAL_ACCURACY = EQUAL_ACCURACY